# https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html

# https://www.elastic.co/guide/en/beats/filebeat/current/configuration-global-options.html
filebeat.spool_size: 2048
filebeat.idle_timeout: 30s

# https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html
filebeat.prospectors:
- input_type: log
  paths:
    - /mnt/log/demo_elastic_search.jl
  multiline.pattern: '^{'
  multiline.negate: true
  multiline.match:  after
  processors:
    - decode_json_fields:
        fields: ['message']
        target: json
  tags: ["cv"]  ## tags for the records
  # fields:
  #   instance_id: "test_instance" ## add extra metadata

# https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html
output.logstash:
  hosts: ["logstash:5044"]