http.host: "0.0.0.0"

xpack.monitoring:
  enabled: true
  elasticsearch:
    url: http://elasticsearch:9200
    username: logstash_system
    password: changeme

pipeline:
  batch:
    size: 1000
    delay: 10

config:
  debug: true
  reload.automatic: true
